# Generated by Django 3.0.8 on 2022-07-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_signdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='signdocument',
            name='page_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
