# Generated by Django 3.0.8 on 2022-07-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_esignmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Document')),
                ('signature', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.ESignModel')),
            ],
        ),
    ]
