# Generated by Django 3.0.8 on 2022-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_esignmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='signdocument',
            name='num_of_signatures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
