# Generated by Django 3.0.8 on 2022-07-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_signdocument_num_of_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigndocument',
            name='num_of_signatures',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
