# Generated by Django 3.0.8 on 2022-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20220726_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='signdocument',
            name='user_signed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
