# Generated by Django 3.0.8 on 2022-07-26 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0010_signdocument_user_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigndocument',
            name='signed_document_url',
            field=models.CharField(default='/media/pdf_documents/GLEN_WRL-LOGBOOk_CURRENT_COMMENTED.pdf', max_length=200),
        ),
        migrations.AddField(
            model_name='signdocument',
            name='signed_document_url',
            field=models.CharField(default='/media/pdf_documents/GLEN_WRL-LOGBOOk_CURRENT_COMMENTED.pdf', max_length=200),
        ),
        migrations.CreateModel(
            name='SendForSigning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
