# Generated by Django 3.0.8 on 2022-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20220726_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigndocument',
            name='signed_document_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signdocument',
            name='signed_document_url',
            field=models.CharField(max_length=200),
        ),
    ]
