# Generated by Django 3.0.8 on 2022-07-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20220726_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendforsigning',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.SignDocument'),
            preserve_default=False,
        ),
    ]
