# Generated by Django 3.0.8 on 2022-07-26 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0013_sendforsigning_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendforsigning',
            name='sender',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
