# Generated by Django 3.0.8 on 2022-07-27 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0018_auto_20220727_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signdocument',
            name='signed_by',
        ),
        migrations.AddField(
            model_name='signdocument',
            name='signed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
