# Generated by Django 3.0.8 on 2022-07-27 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0019_auto_20220727_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signdocument',
            name='signed_by',
            field=models.ManyToManyField(blank=True, related_name='signed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
