# Generated by Django 3.0.8 on 2022-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_auto_20220727_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signdocument',
            name='signed_by',
        ),
        migrations.AddField(
            model_name='signdocument',
            name='signed_by',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
