# Generated by Django 3.0.8 on 2022-07-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0023_auto_20220727_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signdocument',
            name='signed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
