# Generated by Django 3.0.8 on 2022-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_auto_20220727_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendforsigning',
            old_name='user',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='signdocument',
            name='signed_by',
            field=models.CharField(max_length=300),
        ),
    ]
