# Generated by Django 3.0.8 on 2022-07-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0028_signature_signature_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signdocument',
            name='user_signed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
